[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[db.pooler]
enabled = true

[functions.telegram-bot]
enabled = true
verify_jwt = false

[functions.ai-generate]
enabled = true
verify_jwt = true

[functions.send-email]
enabled = true
verify_jwt = true
